apiVersion: apps/v1
kind: Deployment
metadata:
  name: healthcheck-app
spec:
  selector:
    matchLabels:
      app: healthcheck-app
  replicas: 1
  template:
    metadata:
      labels:
        app: healthcheck-app
    spec:
      containers:
      - name: healthcheckappcontainer
        image: "<your-image>"
        ports:
        - containerPort: 5000
        imagePullPolicy: Always
        env:
          - name:  "USERNAME"
            value: "admin"
          - name: "PASSWORD"
            value: "password"
          - name: "CACHE_DURATION_IN_SECONDS"
            value: "30"
          - name: "NODE_ENV"
            value: "production"