apiVersion: apps/v1
kind: Deployment
metadata:
  name: monitoring-app
spec:
  selector:
    matchLabels:
      app: monitoring-app
  replicas: 1
  template:
    metadata:
      labels:
        app: monitoring-app
    spec:
      containers:
      - name: monitoringappcontainer
        image: "<your-repo>/<your-image-name>:<version>"
        ports:
        - containerPort: 5000
        imagePullPolicy: Always
        env:
          - name:  "USERNAME"
            value: "admin"
          - name: "PASSWORD"
            value: "password"
          - name: "CACHE_DURATION_IN_SECONDS"
            value: "30"